In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [6]:
youtube.head()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3

In [7]:
avg = youtube['Avg Video Length (min)']

In [8]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [9]:
type(avg)

pandas.Series

In [10]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

In [11]:
type(avg.value_counts())

pandas.Series

In [10]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [11]:
avg.sort_values(ascending = False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

#### Method Chaining -> we will use multiple methods together to get the required value in a way the first method's output will be second method's input, then 2nd method's output will be 3rd method's input

In [12]:
# which has largest avg video length

avg.sort_values(ascending = False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [14]:
avg.sort_values(ascending = False).head(1).values[0]

np.float64(28.9)

In [16]:
type(avg.sort_values(ascending = False).head(1).values) # numpy array

numpy.ndarray

In [17]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [18]:
### in order to make a change in our data permanent ---> inplace

In [20]:
avg.sort_values(inplace = True)

In [21]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [23]:
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [32]:
df1 = youtube[['Total Videos','Youtuber Name']].squeeze('columns')

In [33]:
df1 = df1.set_index('Youtuber Name')

In [34]:
df1

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [35]:
type(df1)

pandas.DataFrame

In [36]:
df1.squeeze('columns')

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [37]:
df1.sort_index()

                  Total Videos
Youtuber Name
Aaron Archer               136
Aaron Bishop               151
Aaron Brown                 51
Aaron Burns                314
Aaron Carrillo             210
...                        ...
Zachary Phillips           478
Zachary Russell             81
Zachary Shelton            446
Zoe Peterson                78
Zoe Smith                   83

[5000 rows x 1 columns]

In [38]:
df2 = youtube.set_index('Youtuber Name')['Total Videos']

In [39]:
df2

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [40]:
type(df2)

pandas.Series

In [42]:
df2.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int64

In [43]:
subs = youtube['Total Subscribers']

In [44]:
subs

0       8264152
1       8768222
2       6163386
3       4712268
4       9592017
         ...
4995    2665835
4996     136992
4997    2314561
4998    6954832
4999    6785166
Name: Total Subscribers, Length: 5000, dtype: int64

### Mathematical Functions in Pandas

#### 1. sum() ---> sum of all values present in the series
#### 2. product() ---> product of all values present in the series
#### 3. mean() ---> provides us with the averge value of the total column
#### for eg---> Company Data---> Salary ---> average value for that column salary = 7,6,8,9,11 mean

#### 4. median() ---> median provides the idea about the average of the dataa. to reach median, we need to sort the values, the middle valuee is the median.
#### data --> salary ---> 1 crore, 10 crore (outlier) --> avg -> 7+8+6+9
#### outlier ---> that value which is either too big or too small to be called a part of a dataset. such values resut in largee difference between the average and median.

#### mode() --> Mode provides us with the idea that which value is getting repeated maximum number of times.


#### std() ---> provides the idea that how the values inside the series are distributed from the average or mean value - standard deviation
#### salary ---> 7,8,6,6.5,7.5 ----> low standard deviation
#### salary ---> 7,15,4,20,28,17 ----> high standard deviation


#### var() ---> variance also provides the insight about the distribution of the data from the mean value and varance is the square of std.
#### vaariance = (mean - v1)**2 + (mean - v2)**2 +(mean - v3)**2  + .... /(total count of values)

#### variance = std**2

#### min() ---> minimum value in the series
#### max() ---> maximum value in the series

#### describe() ----> describe fn provides the idea about the summary of the important mathematical calculations for the data

#### describe function has :
    min()
    max()
    mean()
    std()
    25%---> 25% of the values out of all the values are less than this specific value
    50%---> 50% of the values out of all the values are less than this specific value
    75%---> 75% of the values out of all the values are less than this specific value
    count() --> total number of rows in the column


### JEE MAINS ---> 25%ile ->my score in JEE Mains was greater than 25% of the people who applied for JEE

In [46]:
subs.sum()

np.int64(25292407967)

In [47]:
subs.product()

np.int64(0)

In [48]:
subs.sort_values()

3595       1755
3204       2910
2470       8649
4584       9029
2615       9436
         ...
3969    9991900
380     9992512
1177    9995049
3593    9999559
1931    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [49]:
subs.mean()

np.float64(5058481.5934)

In [50]:
subs.median()

np.float64(5105967.0)

In [52]:
subs.mode() # jo value sabse zyada baar repeat hui h

0          1755
1          2910
2          8649
3          9029
4          9436
         ...
4995    9991900
4996    9992512
4997    9995049
4998    9999559
4999    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [53]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [54]:
avg.mode()

0    24.1
Name: Avg Video Length (min), dtype: float64

In [56]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
28.0      1
28.1      1
28.3      1
28.4      1
28.9      1
Name: count, Length: 78, dtype: int64

In [57]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [58]:
avg.std()

np.float64(0.8745549483431755)

In [59]:
avg.var()

np.float64(0.7648463576715343)

In [60]:
avg.min()

np.float64(19.1)

In [62]:
avg.max()

np.float64(28.9)

In [63]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [64]:
avg.describe()

count    5000.000000
mean       24.004540
std         0.874555
min        19.100000
25%        23.500000
50%        24.000000
75%        24.500000
max        28.900000
Name: Avg Video Length (min), dtype: float64

## Indexing in Series (to have the access over certain value or values)

#### 1. Positive Indexing (just like list) ----> start from 0 to forward direction
#### 2. NO Negative Indexing
#### 3. Slicing ---> In series we can get the certain values over a given specific range and we can do it using [initial_val : final_val + 1]

#### 4. fancy indexing --> If i want the specific values from the Series, then we can go with the fancy indexing
#### 5. Indexing with Labels ---> A series which is consisting of Labels as the index or custom index, then for this data we can retrieve the info using that custom index or label

In [66]:
avg = avg.sort_index()

In [67]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [68]:
avg[0]

np.float64(24.8)

In [69]:
avg[5]

np.float64(24.2)

In [70]:
avg[-1]

KeyError: -1

In [71]:
avg[7:18]

7     25.6
8     23.1
9     24.2
10    22.9
11    25.4
12    26.9
13    23.4
14    24.1
15    24.9
16    24.7
17    24.8
Name: Avg Video Length (min), dtype: float64

In [72]:
type(avg[7:18])

pandas.Series

In [73]:
type(avg[2])

numpy.float64

In [74]:
### If i want the values skipped at a certain value
avg[2:21:2]

2     24.0
4     24.6
6     23.2
8     23.1
10    22.9
12    26.9
14    24.1
16    24.7
18    23.6
20    24.8
Name: Avg Video Length (min), dtype: float64

In [75]:
### Reverse values in a Series
avg[::-1]

4999    25.2
4998    24.5
4997    25.2
4996    26.3
4995    22.0
        ...
4       24.6
3       24.6
2       24.0
1       22.9
0       24.8
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [76]:
avg[21:2:-2]

21    24.2
19    24.1
17    24.8
15    24.9
13    23.4
11    25.4
9     24.2
7     25.6
5     24.2
3     24.6
Name: Avg Video Length (min), dtype: float64

In [79]:
avg[[2,4,9]]

2    24.0
4    24.6
9    24.2
Name: Avg Video Length (min), dtype: float64

In [80]:
avg[[2,4,9,2001]]

2       24.0
4       24.6
9       24.2
2001    24.8
Name: Avg Video Length (min), dtype: float64

In [82]:
avg[[55,1008,79,56,56]]

55      24.9
1008    23.3
79      25.1
56      23.0
56      23.0
Name: Avg Video Length (min), dtype: float64

In [83]:
df1

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [85]:
df1 = df1.squeeze('columns')

In [86]:
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [88]:
df1['Steve Diaz']

np.int64(182)

In [90]:
df1['Jasmine Smith']

Youtuber Name
Jasmine Smith    244
Jasmine Smith    418
Jasmine Smith    106
Name: Total Videos, dtype: int64

In [91]:
df1[['Steve Diaz','Jasmine Smith', 'Austin Tate']]

Youtuber Name
Steve Diaz       182
Jasmine Smith    244
Jasmine Smith    418
Jasmine Smith    106
Austin Tate       92
Name: Total Videos, dtype: int64

## Editing Series(bring the changes into the values stored inside the Series)

##### 1. Using Indexing ---> df[0]=65 ---> changing the original value at index 0 to 65

In [92]:
df1['Cynthia Harrington']

np.int64(128)

In [93]:
df1['Cynthia Harrington'] = 75

In [94]:
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [95]:
### if indexing does not exist. then what to do

df1['Amit Kumar Singh']

KeyError: 'Amit Kumar Singh'

In [99]:
df1['Amit Kumar Singh'] = 87

In [100]:
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       87
Name: Total Videos, Length: 5001, dtype: int64

In [101]:
#### Slicing in Series ---> df[2:7]=100 ---> 100 value will be associated for index 2 to 6

In [102]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [103]:
avg[1:5]

1    22.9
2    24.0
3    24.6
4    24.6
Name: Avg Video Length (min), dtype: float64

In [104]:
avg[1:5]=100

In [105]:
avg

0        24.8
1       100.0
2       100.0
3       100.0
4       100.0
        ...
4995     22.0
4996     26.3
4997     25.2
4998     24.5
4999     25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [107]:
### Fancy Indexing -->   avg[[2,4,8]] = [45, 84, 79]
avg[[4,4998,4996,0]]

4       100.0
4998     24.5
4996     26.3
0        24.8
Name: Avg Video Length (min), dtype: float64

In [108]:
avg[[4,4998,4996,0]] = [25, 21, 20, 24]

In [109]:
avg

0        24.0
1       100.0
2       100.0
3       100.0
4        25.0
        ...
4995     22.0
4996     20.0
4997     25.2
4998     21.0
4999     25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [110]:
## Index Labelling 
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       87
Name: Total Videos, Length: 5001, dtype: int64

In [112]:
df1[['Eric Patel','Jessica Nelson MD','Amit Kumar Singh']] = [45, 250, 100]

### some error coming up here. We'll learn about it later

InvalidIndexError: Reindexing only valid with uniquely valued Index objects