# Pandas

### Pandas is a powerful library used for data manipulaiton and data analysis. It helps us to work with data in tabular format, just like how we deal with data and spreadsheet in excel or database.

### Pandas provides the functionalities and attributes to clean, organise and analyse huge amountss of data

### why Pandas ?
    Easy to use -> Works like excel inside Python
    Fast -> Handles large data faster than manual methods
    Clean Data -> helps clean, filter and transform messy data
    Integrates well -> Matplotlib, seaborn
    Ideal for ML and AI -> It is ideal for Data Science

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\code\Generative AI course\python\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\code\Generative AI course\python\venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\code\Generative AI course\python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\code\Generative AI course\python\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\code\Generative AI course\python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import  numpy as np
import pandas as pd

### Pandas Series is a column of data in a table like in excel or Google Sheets with labels called as indexes attached to each value

In [8]:
pd.Series([40,50,60], index=['Bread','Milk','Butter'], name='Price of Grocery Items')

Bread     40
Milk      50
Butter    60
Name: Price of Grocery Items, dtype: int64

In [9]:
pd.Series(data = [40,50,60], index=['Bread','Milk','Butter'], name='Price of Grocery Items')

Bread     40
Milk      50
Butter    60
Name: Price of Grocery Items, dtype: int64

In [10]:
## Series is a 1D array that can hold any type of data like integers, float, strings(object),
#  boolean, mixed data type.

#### Data type --> Integers --> Data in a Series(Column) --> Quantity of items in the stock 
#### Data type --> Float --> Data in a series(Column) --> Price or product ratings
#### Data type --> Strings --> Column --> Product Name
#### Data type --> Boolean --> Column --> Is item in stock?
#### Data type --> Dates/times --> Column --> expiry dates or sales dates
#### Mixed Types --> Milk, 40, True in a single column

### Creating a Series in Multiple Ways:
1. List
2. NumPy Array
3. Dictionary
4. Custom Index
5. Scalar value

In [11]:
### Series from list

country = ['India', 'China', 'USA', 'Pakistan']
pd.Series(country)

0       India
1       China
2         USA
3    Pakistan
dtype: str

In [12]:
batsman_runs = [48,64,72,98,114,183]
pd.Series(batsman_runs)

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int64

In [13]:
batsman_runs = [48,64,72,98,114,183]
pd.Series(batsman_runs, dtype = 'int32')

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int32

In [14]:
subject_names = ['Maths','Physics','Chemistry','Biology','English']
subject_marks = [48, 92, 64, 35, 98]

pd.Series(subject_marks, index = subject_names, name = 'Subject Marks Data', dtype = 'int32')

Maths        48
Physics      92
Chemistry    64
Biology      35
English      98
Name: Subject Marks Data, dtype: int32

In [15]:
## Creating a Series using NumPy Array
values = np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [16]:
## Dictionary to Series
## Dictionary is another Data Structure that stores the data in a key value pair and just because 
# it stores the data in a key value pair so we don't have to mention indexes explicitly

In [17]:
data_items = {'Maths' : 78, 'English' : 92, 'Physics' : 88, 'Chemistry': 64}
pd.Series(data_items)

Maths        78
English      92
Physics      88
Chemistry    64
dtype: int64

In [18]:
## custom indexes to series

values = [1,2,3,4,5]
pd.Series(data = values, index = ['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [19]:
## Scalar value inside a series

pd.Series(4, index=['a','b','c','d','e'])

a    4
b    4
c    4
d    4
e    4
dtype: int64

In [20]:
# read_csv() --> this function reads the content from the csv file in pandas so that 
# we can perform the operations on the data or we can perform effective analysis

In [21]:
data = pd.read_csv("C:/code/Generative AI course/Machine Learning/Prerequisites/Pandas/archive/youtube_2025_dataset_202504061614.csv")

In [22]:
data

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [23]:
df = pd.read_csv("youtube_2025_dataset_202504061614.csv")

In [24]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [25]:
## DataFrame ---> Combination of Multiple Series (columns)

In [26]:
## squeeze parameter ---> squeeze parameter makes sure that the data is in series format

In [29]:
pd.read_csv('youtube_one_column.csv')

                     Channel Name
0                 Smith-Ross Labs
1                Sandoval PLC Hub
2     Jones, Moore and Ho Network
3            Mitchell-Hooper Labs
4              Wilson LLC Studios
...                           ...
4995        Flores-Daniel Studios
4996     Spencer and Sons Studios
4997       Obrien-Roberts Studios
4998                 King Ltd Hub
4999            Henry Ltd Studios

[5000 rows x 1 columns]

In [31]:
type(pd.read_csv('youtube_one_column.csv')) # a dataframe
# we need to convert it to Series

pandas.DataFrame

In [34]:
pd.read_csv("youtube_2025_dataset_202504061614.csv", squeeze = True)
# this used to work in pandas till version 2. after it , it was removed

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [37]:
type(pd.read_csv("youtube_one_column.csv").squeeze('columns'))

pandas.Series

In [55]:
df = pd.read_csv("youtube_one_column.csv").squeeze('columns')

In [39]:
# squeeze function converting a Dataframe into Series

In [41]:
pd.read_csv('youtube_two_columns.csv')

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [42]:
# index_col  parameter

In [43]:
df1 = pd.read_csv('youtube_two_columns.csv', index_col = 'Youtuber Name')

In [44]:
df2 = pd.read_csv('youtube_two_columns.csv', index_col = 'Total Videos')

In [47]:
type(df1)

pandas.DataFrame

In [48]:
type(df2)

pandas.DataFrame

In [51]:
# converting dataframe to series

In [52]:
df1

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [61]:
df1 = df1.squeeze('columns') #series

In [53]:
df2.squeeze('columns')

Total Videos
68             Eric Patel
128    Cynthia Harrington
282         Amanda Walker
302     Jessica Nelson MD
129       Matthew Sherman
              ...
106         Jasmine Smith
130        John Rasmussen
179            Lisa Burke
182            Steve Diaz
92            Austin Tate
Name: Youtuber Name, Length: 5000, dtype: str

In [56]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [ ]:
## Attribute in Series

# 1. .values --> representing only the values of the gvien series
# 2. .index --> return only the index values of the given series
# 3. dtype  --> dtype provides the idea about the data type of the values you are storing.
# 4. size ----> this attribute provides the idea about the total number of rows inside the dataset 
# 5. shape ---> this attribute provides the idea about the (row, column) information
# 6. ndim ----> this attribute provides the idea about the dimension of the dataset
# 7. name ----> this ttribute provides the idea about the name of the series
# 8. is_unique --> this provides u the idea of if the values are unique or not inside the column

In [59]:
df.values

<ArrowStringArray>
[                    'Smith-Ross Labs',                    'Sandoval PLC Hub',
         'Jones, Moore and Ho Network',                'Mitchell-Hooper Labs',
                  'Wilson LLC Studios',                   'Myers Ltd Network',
                   'Huber Inc Network',              'Baxter-Collins Studios',
                   'Morrow-Abbott Hub',               'Jackson Group Network',
 ...
                     'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
                      'Baker-Hill Hub',    'Francis, Davis and Jones Network',
     'Whitaker, Horn and Escobar Labs',               'Flores-Daniel Studios',
            'Spencer and Sons Studios',              'Obrien-Roberts Studios',
                        'King Ltd Hub',                   'Henry Ltd Studios']
Length: 5000, dtype: str

In [66]:
df1.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [63]:
# here, df -> series made from 1 column
# df1 -> series made from 2 columns

In [64]:
df.index

RangeIndex(start=0, stop=5000, step=1)

In [65]:
df1.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [67]:
df1.dtype

dtype('int64')

In [68]:
df.dtype

In [70]:
df1 = df1.astype('int32')

In [71]:
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [72]:
df.size

5000

In [73]:
df1.size

5000

In [75]:
df.shape

(5000,)

In [76]:
df1.shape

(5000,)

In [77]:
df1.ndim

1

In [78]:
df.ndim

1

In [79]:
df.name

'Channel Name'

In [80]:
df1.name

'Total Videos'

In [81]:
df1.is_unique

False

In [83]:
df.is_unique

False

In [84]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [85]:
pd.Series([1,2,3,4,5]).is_unique

True

## Series Methods

#### 1. head() --> Provides the top preview of data as the top 5 rows of the dataframe or Series. It is quite helpful with providing the preview of the dataset and if we want to preview top `10 rows, then we can pass 10 as argument, for top 7 rows, pass top 7 rpws as an argument.

#### 2. tail() --> provides the bottom preview of the data as the bottom 5 rows.

#### for eg: dataset ---> salary column ---> top 5 rows ---> salary --> 7 lpa ---> top 10 --> top 15,,,  tail()---> bottom 5 rows --> salary --> 4 lpa, 9 lpa  

#### 3. sample()  ---> sample() provides any custom row from the dataset for us to preview it

#### value_counts() ---> it provides the idea about the count of the values(categorical values). if i am havng a column where i want to calculate categorical value count then i will go with value_counts(). 

#### sort_values() ---> this method sorts the values in an ascending manner. It can be useful for us for the numerical columns. you can even sort the values in descending manner as well.

#### sort_index() ---> this method sorts the index of the dataset

In [87]:
df1

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [88]:
df1.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int32

In [89]:
df1.head(7)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Name: Total Videos, dtype: int32

In [90]:
df1.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int32

In [92]:
df.head()

0                Smith-Ross Labs
1               Sandoval PLC Hub
2    Jones, Moore and Ho Network
3           Mitchell-Hooper Labs
4             Wilson LLC Studios
Name: Channel Name, dtype: str

In [93]:
df.tail()

4995       Flores-Daniel Studios
4996    Spencer and Sons Studios
4997      Obrien-Roberts Studios
4998                King Ltd Hub
4999           Henry Ltd Studios
Name: Channel Name, dtype: str

In [94]:
df.tail(11)

4989                   Knight and Sons Labs
4990                        Cole-Sharp Labs
4991    Sherman, Mcgee and Phillips Studios
4992                         Baker-Hill Hub
4993       Francis, Davis and Jones Network
4994        Whitaker, Horn and Escobar Labs
4995                  Flores-Daniel Studios
4996               Spencer and Sons Studios
4997                 Obrien-Roberts Studios
4998                           King Ltd Hub
4999                      Henry Ltd Studios
Name: Channel Name, dtype: str

In [99]:
df.sample(5)

65                        Fuentes-Schmitt Hub
4953                      Meza-Martin Studios
3310                  Sandoval-Rodriguez Labs
4779    Richardson, White and Wallace Network
3477                      Murray and Sons Hub
Name: Channel Name, dtype: str

In [104]:
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [107]:
youtube.head()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3

In [108]:
type(youtube)

pandas.DataFrame

In [109]:
youtube.shape

(5000, 14)

In [111]:
print(youtube.head())

                  Channel Name       Youtuber Name  Total Videos  \
0              Smith-Ross Labs          Eric Patel            68
1             Sandoval PLC Hub  Cynthia Harrington           128
2  Jones, Moore and Ho Network       Amanda Walker           282
3         Mitchell-Hooper Labs   Jessica Nelson MD           302
4           Wilson LLC Studios     Matthew Sherman           129

                           Best Video  Avg Video Length (min)  \
0           VR Challenge: Review 2023                    24.8
1  Nanotech Simulation: Analysis 2024                    22.9
2  Metaverse Interface: Analysis 2024                    24.0
3            VR Protocol: Review 2023                    24.6
4    Nanotech Simulation: Review 2024                    24.6

   Total Subscribers  Members Count  AI Generated Content (%)  \
0            8264152         303319                         9
1            8768222         384629                        62
2            6163386         361743                        31
3            4712268          58483                         5
4            9592017         333873                        63

   Neural Interface Compatible Metaverse Integration Level  \
0                         True                        Full
1                        False                         NaN
2                         True                    Advanced
3                        False                         NaN
4                         True                         NaN

   Quantum Computing Topics Holographic Content Rating  Engagement Score  \
0                         5                         3D         130655.44
1                         4                         3D         138624.73
2                         6                         1D          97442.53
3                        15                         1D          74500.50
4                        12                         3D         151648.85

   Content Value Index
0                  6.2
1                 21.4
2                 13.5
3                 12.0
4                 27.3

In [1]:
df1

NameError: name 'df1' is not defined